name: Tests

on:
  pull_request:
    branches: [ 'dev', 'main' ]

jobs:
  api_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Setup Mongodb
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "6.0"

      - name: Run API tests
        run: |
          npm install
          npm test
        working-directory: ./api
        env:
          REDISSTORESECRET: ${{ secrets.REDISSTORESECRET }}
          MONGOURI: "mongodb://localhost:27017"
        

  ui_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
        working-directory: ./front-end
