
      - name: setup & run dagger pipeline
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r ci/requirements.txt
      - run: python ci/pipeline.py --no-login --tag=${{ env.DOCKER_IMAGE_TAG }}