name: Build

on:
  push:
    branches: [ 'main', 'dev' ]

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v3

      - name: set image tag from branch
        run: |
          if [[ $GITHUB_REF == 'refs/head/main' ]]; then
            echo "DOCKER_IMAGE_TAG=latest" >> "$GITHUB_ENV"
          elif [[ $GITHUB_REF == 'refs/head/dev' ]]; then
            echo "DOCKER_IMAGE_TAG=dev" >> "$GITHUB_ENV"
          else
            echo "DOCKER_IMAGE_TAG=unstable" >> "$GITHUB_ENV"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: setup & run dagger pipeline
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r ci/requirements.txt
      - run: python ci/pipeline.py --no-login --tag=${{ env.DOCKER_IMAGE_TAG }}