name: Run Dagger Build Pipeling

on:
  push:
    branches: [ 'main', 'anthonyM' ]

  jobs:
    dagger:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Current Repo
          uses: actions/checkout@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: install pipeline deps
          run: pip install -r ci/requirements.txt

        - name: set image tag from branch
          run: |
            if [[ $GITHUB_REF == 'refs/head/main' ]]; then
              echo "DOCKER_IMAGE_TAG=latest" >> "$GITHUB_ENV"
            else
              echo "DOCKER_IMAGE_TAG=develop" >> "$GITHUB_ENV"
            fi

        - name: run dagger pipeline
          run: python ci/pipeline.py --login=False --tag=${{ GITHUB_ENV.DOCKER_IMAGE_TAG }}

        - name: upload bundle as artifact
          uses: actions/upload-artifact@v3
          with:
            name: server-bundle
            path: ./dist
            retention-days: 1

